fixtures:
  forge_modules:
    apt: puppetlabs/apt
    stdlib: puppetlabs/stdlib
    epel: stahnma/epel
    augeasproviders_sysctl: herculesteam/augeasproviders_sysctl
    augeasproviders_core: herculesteam/augeasproviders_core
  symlinks:
    redis: "#{source_dir}"

