fixtures:
  repositories:
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    epel: 'https://github.com/voxpupuli/puppet-epel.git'
    augeas_core:
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core"
      puppet_version: ">= 6.0.0"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
    systemd: 'https://github.com/camptocamp/puppet-systemd.git'
