fixtures:
  repositories:
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: 6.3.0
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: 5.2.0
    epel:
      repo: 'https://github.com/stahnma/puppet-module-epel.git'
      ref: 1.3.1
    augeasproviders_sysctl:
      repo: "git://github.com/hercules-team/augeasproviders_sysctl.git"
      tag: v2.3.1
    augeasproviders_core:
      repo: "git://github.com/hercules-team/augeasproviders_core.git"
      tag: v2.4.0
  symlinks:
    redis: "#{source_dir}"

